[2024-12-03T17:21:45.103+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: practicional_dag.process_user scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:21:45.116+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: practicional_dag.process_user scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:21:45.116+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-03T17:21:45.117+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-03T17:21:45.117+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-03T17:21:45.132+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): process_user> on 2024-12-02 00:00:00+00:00
[2024-12-03T17:21:45.137+0000] {standard_task_runner.py:55} INFO - Started process 2715 to run task
[2024-12-03T17:21:45.142+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'practicional_dag', 'process_user', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp7_4c5r7h']
[2024-12-03T17:21:45.145+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask process_user
[2024-12-03T17:21:45.236+0000] {task_command.py:376} INFO - Running <TaskInstance: practicional_dag.process_user scheduled__2024-12-02T00:00:00+00:00 [running]> on host 305bd4985967
[2024-12-03T17:21:45.335+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=practicional_dag
AIRFLOW_CTX_TASK_ID=process_user
AIRFLOW_CTX_EXECUTION_DATE=2024-12-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-02T00:00:00+00:00
[2024-12-03T17:21:45.352+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 23, in _process_user
    user = user['results'][0]
TypeError: 'NoneType' object is not subscriptable
[2024-12-03T17:21:45.366+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=practicional_dag, task_id=process_user, execution_date=20241202T000000, start_date=20241203T172145, end_date=20241203T172145
[2024-12-03T17:21:45.381+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 7 for task process_user ('NoneType' object is not subscriptable; 2715)
[2024-12-03T17:21:45.406+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-12-03T17:21:45.431+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T17:34:10.797+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: practicional_dag.process_user scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:34:10.808+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: practicional_dag.process_user scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:34:10.808+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-03T17:34:10.809+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-12-03T17:34:10.809+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-03T17:34:10.822+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): process_user> on 2024-12-02 00:00:00+00:00
[2024-12-03T17:34:10.827+0000] {standard_task_runner.py:55} INFO - Started process 3300 to run task
[2024-12-03T17:34:10.831+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'practicional_dag', 'process_user', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpx5kz0ryp']
[2024-12-03T17:34:10.834+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask process_user
[2024-12-03T17:34:10.916+0000] {task_command.py:376} INFO - Running <TaskInstance: practicional_dag.process_user scheduled__2024-12-02T00:00:00+00:00 [running]> on host 305bd4985967
[2024-12-03T17:34:11.002+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=practicional_dag
AIRFLOW_CTX_TASK_ID=process_user
AIRFLOW_CTX_EXECUTION_DATE=2024-12-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-02T00:00:00+00:00
[2024-12-03T17:34:11.064+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-12-03T17:34:11.076+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=practicional_dag, task_id=process_user, execution_date=20241202T000000, start_date=20241203T173410, end_date=20241203T173411
[2024-12-03T17:34:11.133+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-12-03T17:34:11.184+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
